name: CI

on:
  push:
    branches:
      - main
      - feature-branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: feature-branch

    - name: Run script
      run: ./import_results_cloud.sh
